### ISSUE TITLE
./scripts/colorize.real.sh error 

### ISSUE THREAD

**Issue by AlexanderKozhevin** [KIMGEONUNG/BigColor#6]
Hello, sorry I'm trying to run an inference.
But getting the following error. 
I downloaded all required checkpoints.
And input folder contain images.
My test server use nvidia T4

Would be grateful for any help 🙏
```
/scripts/colorize.real.sh
Target Epoch is 011
Adding attention layer in G at resolution 64
Use pretraind G
Use EMA
Traceback (most recent call last):
  File "colorize_real.py", line 248, in <module>
    main(args)
  File "colorize_real.py", line 99, in main
    classifier = timm.create_model(
  File "/home/ubuntu/anaconda3/envs/bigcolor/lib/python3.8/site-packages/timm/models/factory.py", line 71, in create_model
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
  File "/home/ubuntu/anaconda3/envs/bigcolor/lib/python3.8/site-packages/timm/models/efficientnet.py", line 2013, in tf_efficientnet_l2_ns_475
    model = _gen_efficientnet(
  File "/home/ubuntu/anaconda3/envs/bigcolor/lib/python3.8/site-packages/timm/models/efficientnet.py", line 880, in _gen_efficientnet
    model = _create_effnet(variant, pretrained, **model_kwargs)
  File "/home/ubuntu/anaconda3/envs/bigcolor/lib/python3.8/site-packages/timm/models/efficientnet.py", line 629, in _create_effnet
    model = build_model_with_cfg(
  File "/home/ubuntu/anaconda3/envs/bigcolor/lib/python3.8/site-packages/timm/models/helpers.py", line 545, in build_model_with_cfg
    load_pretrained(
  File "/home/ubuntu/anaconda3/envs/bigcolor/lib/python3.8/site-packages/timm/models/helpers.py", line 245, in load_pretrained
    state_dict = load_state_dict_from_url(
  File "/home/ubuntu/anaconda3/envs/bigcolor/lib/python3.8/site-packages/torch/hub.py", line 590, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/ubuntu/anaconda3/envs/bigcolor/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/bigcolor/lib/python3.8/site-packages/torch/serialization.py", line 794, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 523912 more bytes. The file might be corrupted.

```

**Comment by AlexanderKozhevin** [comment]
Nevermind, it was problem with pytorch cache. 
I had to remove /home/ubuntu/.cache/torch/hub/checkpoints/tf_efficientnet_l2_ns_475-bebbd00a.pth
